In [ ]:

from google.colab import files
uploaded=files.upload()

Saving battery_cycle_level_dataset_CLEAN_FINAL.csv to battery_cycle_level_dataset_CLEAN_FINAL.csv

In [ ]:
import pandas as pd
df=pd.read_csv("battery_cycle_level_dataset_CLEAN_FINAL.csv")
df.head()

  battery_id  cycle   voltage  temperature  capacity       soh  rul
0      B0005      1  3.532781    32.536891  1.861976  1.000000  167
1      B0005      2  3.542968    32.643595  1.851862  0.994568  166
2      B0005      3  3.553056    32.522526  1.840808  0.988631  165
3      B0005      4  3.545849    32.492083  1.850058  0.993599  164
4      B0005      5  3.544456    32.368612  1.849432  0.993263  163

In [ ]:
print(df)

     battery_id  cycle   voltage  temperature  capacity       soh  rul
0         B0005      1  3.532781    32.536891  1.861976  1.000000  167
1         B0005      2  3.542968    32.643595  1.851862  0.994568  166
2         B0005      3  3.553056    32.522526  1.840808  0.988631  165
3         B0005      4  3.545849    32.492083  1.850058  0.993599  164
4         B0005      5  3.544456    32.368612  1.849432  0.993263  163
...         ...    ...       ...          ...       ...       ...  ...
1410      B0053     54  3.080080    12.530864  1.292799  0.988320    1
1411      B0053     55  3.063813    12.900294  1.312809  1.003617    0
1412      B0054      1  3.205983    12.489230  0.853855  1.000000    0
1413      B0055      1  3.153346    12.207199  0.854758  1.000000    0
1414      B0056      1  3.241611    10.334364  0.794083  1.000000    0

[1415 rows x 7 columns]

experiment 1

First databse

In [ ]:
from google.colab import files
uploaded=files.upload()

Saving medical-charges.csv to medical-charges.csv

In [ ]:
import pandas as pd
df=pd.read_csv("medical-charges.csv")
df.head()

   age     sex     bmi  children smoker     region      charges
0   19  female  27.900         0    yes  southwest  16884.92400
1   18    male  33.770         1     no  southeast   1725.55230
2   28    male  33.000         3     no  southeast   4449.46200
3   33    male  22.705         0     no  northwest  21984.47061
4   32    male  28.880         0     no  northwest   3866.85520

In [ ]:
print(df)

      age     sex     bmi  children smoker     region      charges
0      19  female  27.900         0    yes  southwest  16884.92400
1      18    male  33.770         1     no  southeast   1725.55230
2      28    male  33.000         3     no  southeast   4449.46200
3      33    male  22.705         0     no  northwest  21984.47061
4      32    male  28.880         0     no  northwest   3866.85520
...   ...     ...     ...       ...    ...        ...          ...
1333   50    male  30.970         3     no  northwest  10600.54830
1334   18  female  31.920         0     no  northeast   2205.98080
1335   18  female  36.850         0     no  southeast   1629.83350
1336   21  female  25.800         0     no  southwest   2007.94500
1337   61  female  29.070         0    yes  northwest  29141.36030

[1338 rows x 7 columns]

In [ ]:
#first five records



import pandas as pd
from google.colab import files
uploaded = files.upload()
df = pd.read_csv("medical-charges.csv")
print("First five records in the dataset:")
print(df.head(5))

Saving medical-charges.csv to medical-charges (2).csv
First five records in the dataset:
   age     sex     bmi  children smoker     region      charges
0   19  female  27.900         0    yes  southwest  16884.92400
1   18    male  33.770         1     no  southeast   1725.55230
2   28    male  33.000         3     no  southeast   4449.46200
3   33    male  22.705         0     no  northwest  21984.47061
4   32    male  28.880         0     no  northwest   3866.85520

In [ ]:
#first 10 records


import pandas as pd
from google.colab import files
uploaded = files.upload()
df = pd.read_csv("medical-charges.csv")
print("First five records in the dataset:")
print(df.head(10))

Saving medical-charges.csv to medical-charges (3).csv
First five records in the dataset:
   age     sex     bmi  children smoker     region      charges
0   19  female  27.900         0    yes  southwest  16884.92400
1   18    male  33.770         1     no  southeast   1725.55230
2   28    male  33.000         3     no  southeast   4449.46200
3   33    male  22.705         0     no  northwest  21984.47061
4   32    male  28.880         0     no  northwest   3866.85520
5   31  female  25.740         0     no  southeast   3756.62160
6   46  female  33.440         1     no  southeast   8240.58960
7   37  female  27.740         3     no  northwest   7281.50560
8   37    male  29.830         2     no  northeast   6406.41070
9   60  female  25.840         0     no  northwest  28923.13692

In [ ]:
#last 5 records


import pandas as pd
from google.colab import files
uploaded = files.upload()
df = pd.read_csv("medical-charges.csv")
print("Last five records in the dataset:")
print(df.tail(5))

Saving medical-charges.csv to medical-charges (4).csv
Last five records in the dataset:
      age     sex    bmi  children smoker     region     charges
1333   50    male  30.97         3     no  northwest  10600.5483
1334   18  female  31.92         0     no  northeast   2205.9808
1335   18  female  36.85         0     no  southeast   1629.8335
1336   21  female  25.80         0     no  southwest   2007.9450
1337   61  female  29.07         0    yes  northwest  29141.3603

In [ ]:
#last 10 records


import pandas as pd
from google.colab import files
uploaded = files.upload()
df = pd.read_csv("medical-charges.csv")
print("Last ten records in the dataset:")
print(df.tail(10))

Saving medical-charges.csv to medical-charges (5).csv
Last ten records in the dataset:
      age     sex     bmi  children smoker     region      charges
1328   23  female  24.225         2     no  northeast  22395.74424
1329   52    male  38.600         2     no  southwest  10325.20600
1330   57  female  25.740         2     no  southeast  12629.16560
1331   23  female  33.400         0     no  southwest  10795.93733
1332   52  female  44.700         3     no  southwest  11411.68500
1333   50    male  30.970         3     no  northwest  10600.54830
1334   18  female  31.920         0     no  northeast   2205.98080
1335   18  female  36.850         0     no  southeast   1629.83350
1336   21  female  25.800         0     no  southwest   2007.94500
1337   61  female  29.070         0    yes  northwest  29141.36030

In [ ]:
#random 5 rows


import pandas as pd
from google.colab import files
uploaded = files.upload()
df = pd.read_csv("medical-charges.csv")
print("Random five rows in the dataset:")
print(df.sample(5))

Saving medical-charges.csv to medical-charges (6).csv
Random five records in the dataset:
     age     sex     bmi  children smoker     region      charges
394   46  female  32.300         2     no  northeast   9411.00500
744   50    male  26.410         0     no  northwest   8827.20990
561   54  female  32.680         0     no  northeast  10923.93320
623   18    male  33.535         0    yes  northeast  34617.84065
85    45    male  22.895         2    yes  northwest  21098.55405

In [ ]:
#shape


import pandas as pd
from google.colab import files
uploaded = files.upload()
df = pd.read_csv("medical-charges.csv")
print("Shape of the dataset (rows, columns):")
print(df.shape)

Saving medical-charges.csv to medical-charges (7).csv
Shape of the dataset (rows, columns):
(1338, 7)

In [ ]:
#coloumns names


import pandas as pd
from google.colab import files
uploaded = files.upload()
df = pd.read_csv("medical-charges.csv")
print("Column names:")
print(df.columns)

Saving medical-charges.csv to medical-charges (8).csv
Column names:
Index(['age', 'sex', 'bmi', 'children', 'smoker', 'region', 'charges'], dtype='object')

In [ ]:
#datatypes



import pandas as pd
from google.colab import files
uploaded = files.upload()
df = pd.read_csv("medical-charges.csv")
print("Data types of each column:")
print(df.dtypes)

Saving medical-charges.csv to medical-charges (9).csv
Data types of each column:
age           int64
sex          object
bmi         float64
children      int64
smoker       object
region       object
charges     float64
dtype: object

In [ ]:
#sumary


import pandas as pd
from google.colab import files
uploaded = files.upload()
df = pd.read_csv("medical-charges.csv")
print("the sumary of the databse:")
print(df.info())

Saving medical-charges.csv to medical-charges (10).csv
the sumary of the databse:
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1338 entries, 0 to 1337
Data columns (total 7 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   age       1338 non-null   int64
 1   sex       1338 non-null   object
 2   bmi       1338 non-null   float64
 3   children  1338 non-null   int64
 4   smoker    1338 non-null   object
 5   region    1338 non-null   object
 6   charges   1338 non-null   float64
dtypes: float64(2), int64(2), object(3)
memory usage: 73.3+ KB
None

In [ ]:
#statistical values


import pandas as pd
from google.colab import files
uploaded = files.upload()
df = pd.read_csv("medical-charges.csv")
print("numerical statistics:")
print(df.describe())

Saving medical-charges.csv to medical-charges (12).csv
numerical statistics:
               age          bmi     children       charges
count  1338.000000  1338.000000  1338.000000   1338.000000
mean     39.207025    30.663397     1.094918  13270.422265
std      14.049960     6.098187     1.205493  12110.011237
min      18.000000    15.960000     0.000000   1121.873900
25%      27.000000    26.296250     0.000000   4740.287150
50%      39.000000    30.400000     1.000000   9382.033000
75%      51.000000    34.693750     2.000000  16639.912515
max      64.000000    53.130000     5.000000  63770.428010

In [ ]:
#statistic includiing all catagorical coloum


import pandas as pd
from google.colab import files
uploaded = files.upload()
df = pd.read_csv("medical-charges.csv")
print("statistic includiing all catagorical coloum:")
print(df.describe(include="all"))

Saving medical-charges.csv to medical-charges (13).csv
statistic includiing all catagorical coloum:
                age   sex          bmi     children smoker     region  \
count   1338.000000  1338  1338.000000  1338.000000   1338       1338
unique          NaN     2          NaN          NaN      2          4
top             NaN  male          NaN          NaN     no  southeast
freq            NaN   676          NaN          NaN   1064        364
mean      39.207025   NaN    30.663397     1.094918    NaN        NaN
std       14.049960   NaN     6.098187     1.205493    NaN        NaN
min       18.000000   NaN    15.960000     0.000000    NaN        NaN
25%       27.000000   NaN    26.296250     0.000000    NaN        NaN
50%       39.000000   NaN    30.400000     1.000000    NaN        NaN
75%       51.000000   NaN    34.693750     2.000000    NaN        NaN
max       64.000000   NaN    53.130000     5.000000    NaN        NaN

             charges
count    1338.000000
unique           NaN
top              NaN
freq             NaN
mean    13270.422265
std     12110.011237
min      1121.873900
25%      4740.287150
50%      9382.033000
75%     16639.912515
max     63770.428010

In [ ]:
#unique value conuts per column


import pandas as pd
from google.colab import files
uploaded = files.upload()
df = pd.read_csv("medical-charges.csv")
print("Unique value counts per column:")
print(df.nunique())

Saving medical-charges.csv to medical-charges (14).csv
Unique value counts per column:
age           47
sex            2
bmi          548
children       6
smoker         2
region         4
charges     1337
dtype: int64

In [ ]:
#missing value


import pandas as pd
from google.colab import files
uploaded = files.upload()
df = pd.read_csv("medical-charges.csv")
print("Missing values per column:")
print(df.isnull().sum())

Saving medical-charges.csv to medical-charges (15).csv
Missing values per column:
age         0
sex         0
bmi         0
children    0
smoker      0
region      0
charges     0
dtype: int64

In [ ]:
#min max mean sd percentile


import pandas as pd
from google.colab import files
uploaded = files.upload()
df = pd.read_csv("medical-charges.csv")
col = "age"
print(f"Statistics for column: {col}")
print("Mean:", df[col].mean())
print("Min:", df[col].min())
print("Max:", df[col].max())
print("Standard Deviation:", df[col].std())
print("25th Percentile:", df[col].quantile(0.25))

Saving medical-charges.csv to medical-charges (17).csv
Statistics for column: age
Mean: 39.20702541106129
Min: 18
Max: 64
Standard Deviation: 14.049960379216172
25th Percentile: 27.0

In [21]:
import pandas as pd
from google.colab import files
uploaded = files.upload()
df1 = pd.read_csv("medical-charges.csv")
from google.colab import files
uploaded = files.upload()
df2 = pd.read_csv("insurance.csv")

merged_df = pd.merge(df1, df2, on="age")

Saving medical-charges.csv to medical-charges (3).csv

Saving insurance.csv to insurance (15).csv

In [22]:
# Show first 5 rows of merged dataset


print("First five records in merged dataset:")
print(merged_df.head(5))

First five records in merged dataset:
   age   sex_x  bmi_x  children_x smoker_x   region_x  charges_x   sex_y  \
0   19  female   27.9           0      yes  southwest  16884.924  female
1   19  female   27.9           0      yes  southwest  16884.924    male
2   19  female   27.9           0      yes  southwest  16884.924  female
3   19  female   27.9           0      yes  southwest  16884.924    male
4   19  female   27.9           0      yes  southwest  16884.924  female

    bmi_y  children_y smoker_y   region_y    charges_y
0  27.900           0      yes  southwest  16884.92400
1  24.600           1       no  southwest   1837.23700
2  28.600           5       no  southwest   4687.79700
3  20.425           0       no  northwest   1625.43375
4  28.900           0       no  southwest   1743.21400

Second database

In [ ]:
from google.colab import files
uploaded=files.upload()

Saving insurance.csv to insurance.csv

In [ ]:
import pandas as pd
df=pd.read_csv("insurance.csv")
df.head()

   age     sex     bmi  children smoker     region      charges
0   19  female  27.900         0    yes  southwest  16884.92400
1   18    male  33.770         1     no  southeast   1725.55230
2   28    male  33.000         3     no  southeast   4449.46200
3   33    male  22.705         0     no  northwest  21984.47061
4   32    male  28.880         0     no  northwest   3866.85520

In [ ]:
print(df)

      age     sex     bmi  children smoker     region      charges
0      19  female  27.900         0    yes  southwest  16884.92400
1      18    male  33.770         1     no  southeast   1725.55230
2      28    male  33.000         3     no  southeast   4449.46200
3      33    male  22.705         0     no  northwest  21984.47061
4      32    male  28.880         0     no  northwest   3866.85520
...   ...     ...     ...       ...    ...        ...          ...
1333   50    male  30.970         3     no  northwest  10600.54830
1334   18  female  31.920         0     no  northeast   2205.98080
1335   18  female  36.850         0     no  southeast   1629.83350
1336   21  female  25.800         0     no  southwest   2007.94500
1337   61  female  29.070         0    yes  northwest  29141.36030

[1338 rows x 7 columns]

In [ ]:
#first five records



import pandas as pd
from google.colab import files
uploaded = files.upload()
df = pd.read_csv("insurance.csv")
print("First five records in the dataset:")
print(df.head(5))

Saving insurance.csv to insurance (1).csv
First five records in the dataset:
   age     sex     bmi  children smoker     region      charges
0   19  female  27.900         0    yes  southwest  16884.92400
1   18    male  33.770         1     no  southeast   1725.55230
2   28    male  33.000         3     no  southeast   4449.46200
3   33    male  22.705         0     no  northwest  21984.47061
4   32    male  28.880         0     no  northwest   3866.85520

In [ ]:
#first 10 records


import pandas as pd
from google.colab import files
uploaded = files.upload()
df = pd.read_csv("insurance.csv")
print("First five records in the dataset:")
print(df.head(10))

Saving insurance.csv to insurance (2).csv
First five records in the dataset:
   age     sex     bmi  children smoker     region      charges
0   19  female  27.900         0    yes  southwest  16884.92400
1   18    male  33.770         1     no  southeast   1725.55230
2   28    male  33.000         3     no  southeast   4449.46200
3   33    male  22.705         0     no  northwest  21984.47061
4   32    male  28.880         0     no  northwest   3866.85520
5   31  female  25.740         0     no  southeast   3756.62160
6   46  female  33.440         1     no  southeast   8240.58960
7   37  female  27.740         3     no  northwest   7281.50560
8   37    male  29.830         2     no  northeast   6406.41070
9   60  female  25.840         0     no  northwest  28923.13692

In [ ]:
#last 5 records


import pandas as pd
from google.colab import files
uploaded = files.upload()
df = pd.read_csv("insurance.csv")
print("Last five records in the dataset:")
print(df.tail(5))

Saving insurance.csv to insurance (3).csv
Last five records in the dataset:
      age     sex    bmi  children smoker     region     charges
1333   50    male  30.97         3     no  northwest  10600.5483
1334   18  female  31.92         0     no  northeast   2205.9808
1335   18  female  36.85         0     no  southeast   1629.8335
1336   21  female  25.80         0     no  southwest   2007.9450
1337   61  female  29.07         0    yes  northwest  29141.3603

In [ ]:
#last 10 records


import pandas as pd
from google.colab import files
uploaded = files.upload()
df = pd.read_csv("insurance.csv")
print("Last ten records in the dataset:")
print(df.tail(10))

Saving insurance.csv to insurance (4).csv
Last ten records in the dataset:
      age     sex     bmi  children smoker     region      charges
1328   23  female  24.225         2     no  northeast  22395.74424
1329   52    male  38.600         2     no  southwest  10325.20600
1330   57  female  25.740         2     no  southeast  12629.16560
1331   23  female  33.400         0     no  southwest  10795.93733
1332   52  female  44.700         3     no  southwest  11411.68500
1333   50    male  30.970         3     no  northwest  10600.54830
1334   18  female  31.920         0     no  northeast   2205.98080
1335   18  female  36.850         0     no  southeast   1629.83350
1336   21  female  25.800         0     no  southwest   2007.94500
1337   61  female  29.070         0    yes  northwest  29141.36030

In [11]:
#random 5 rows


import pandas as pd
from google.colab import files
uploaded = files.upload()
df = pd.read_csv("insurance.csv")
print("Random five rows in the dataset:")
print(df.sample(5))

Saving insurance.csv to insurance (5).csv
Random five rows in the dataset:
      age     sex     bmi  children smoker     region      charges
1125   63  female  25.080         0     no  northwest  14254.60820
1161   34    male  42.130         2     no  southeast   5124.18870
957    24    male  26.790         1     no  northwest  12609.88702
1311   33  female  26.695         0     no  northwest   4571.41305
191    36  female  26.200         0     no  southwest   4883.86600

In [12]:
#shape


import pandas as pd
from google.colab import files
uploaded = files.upload()
df = pd.read_csv("insurance.csv")
print("Shape of the dataset (rows, columns):")
print(df.shape)

Saving insurance.csv to insurance (6).csv
Shape of the dataset (rows, columns):
(1338, 7)

In [13]:
#coloumns names


import pandas as pd
from google.colab import files
uploaded = files.upload()
df = pd.read_csv("medical-charges.csv")
print("Column names:")
print(df.columns)

Saving insurance.csv to insurance (7).csv
Column names:
Index(['age', 'sex', 'bmi', 'children', 'smoker', 'region', 'charges'], dtype='object')

In [14]:
#datatypes



import pandas as pd
from google.colab import files
uploaded = files.upload()
df = pd.read_csv("insurance.csv")
print("Data types of each column:")
print(df.dtypes)

Saving insurance.csv to insurance (8).csv
Data types of each column:
age           int64
sex          object
bmi         float64
children      int64
smoker       object
region       object
charges     float64
dtype: object

In [15]:
#sumary


import pandas as pd
from google.colab import files
uploaded = files.upload()
df = pd.read_csv("insurance.csv")
print("the sumary of the databse:")
print(df.info())

Saving insurance.csv to insurance (9).csv
the sumary of the databse:
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1338 entries, 0 to 1337
Data columns (total 7 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   age       1338 non-null   int64
 1   sex       1338 non-null   object
 2   bmi       1338 non-null   float64
 3   children  1338 non-null   int64
 4   smoker    1338 non-null   object
 5   region    1338 non-null   object
 6   charges   1338 non-null   float64
dtypes: float64(2), int64(2), object(3)
memory usage: 73.3+ KB
None

In [16]:
#statistical values


import pandas as pd
from google.colab import files
uploaded = files.upload()
df = pd.read_csv("insurance.csv")
print("numerical statistics:")
print(df.describe())

Saving insurance.csv to insurance (10).csv
numerical statistics:
               age          bmi     children       charges
count  1338.000000  1338.000000  1338.000000   1338.000000
mean     39.207025    30.663397     1.094918  13270.422265
std      14.049960     6.098187     1.205493  12110.011237
min      18.000000    15.960000     0.000000   1121.873900
25%      27.000000    26.296250     0.000000   4740.287150
50%      39.000000    30.400000     1.000000   9382.033000
75%      51.000000    34.693750     2.000000  16639.912515
max      64.000000    53.130000     5.000000  63770.428010

In [17]:
#statistic includiing all catagorical coloum


import pandas as pd
from google.colab import files
uploaded = files.upload()
df = pd.read_csv("insurance.csv")
print("statistic includiing all catagorical coloum:")
print(df.describe(include="all"))

Saving insurance.csv to insurance (11).csv
statistic includiing all catagorical coloum:
                age   sex          bmi     children smoker     region  \
count   1338.000000  1338  1338.000000  1338.000000   1338       1338
unique          NaN     2          NaN          NaN      2          4
top             NaN  male          NaN          NaN     no  southeast
freq            NaN   676          NaN          NaN   1064        364
mean      39.207025   NaN    30.663397     1.094918    NaN        NaN
std       14.049960   NaN     6.098187     1.205493    NaN        NaN
min       18.000000   NaN    15.960000     0.000000    NaN        NaN
25%       27.000000   NaN    26.296250     0.000000    NaN        NaN
50%       39.000000   NaN    30.400000     1.000000    NaN        NaN
75%       51.000000   NaN    34.693750     2.000000    NaN        NaN
max       64.000000   NaN    53.130000     5.000000    NaN        NaN

             charges
count    1338.000000
unique           NaN
top              NaN
freq             NaN
mean    13270.422265
std     12110.011237
min      1121.873900
25%      4740.287150
50%      9382.033000
75%     16639.912515
max     63770.428010

In [18]:
#unique value conuts per column


import pandas as pd
from google.colab import files
uploaded = files.upload()
df = pd.read_csv("insurance.csv")
print("Unique value counts per column:")
print(df.nunique())

Saving insurance.csv to insurance (12).csv
Unique value counts per column:
age           47
sex            2
bmi          548
children       6
smoker         2
region         4
charges     1337
dtype: int64

In [19]:
#missing value


import pandas as pd
from google.colab import files
uploaded = files.upload()
df = pd.read_csv("insurance.csv")
print("Missing values per column:")
print(df.isnull().sum())

Saving insurance.csv to insurance (13).csv
Missing values per column:
age         0
sex         0
bmi         0
children    0
smoker      0
region      0
charges     0
dtype: int64

In [20]:
#min max mean sd percentile


import pandas as pd
from google.colab import files
uploaded = files.upload()
df = pd.read_csv("insurance.csv")
col = "age"
print(f"Statistics for column: {col}")
print("Mean:", df[col].mean())
print("Min:", df[col].min())
print("Max:", df[col].max())
print("Standard Deviation:", df[col].std())
print("25th Percentile:", df[col].quantile(0.25))

Saving insurance.csv to insurance (14).csv
Statistics for column: age
Mean: 39.20702541106129
Min: 18
Max: 64
Standard Deviation: 14.049960379216172
25th Percentile: 27.0